name: MinecraftDiscordSynchronisation
version: '1.0'
main: de.peaqe.minecraftDiscordSynchronisation.MinecraftDiscordSynchronisation
api-version: '1.21'
authors: [ peaqe ]

commands:
  verify:
    description: "Verknüpfe dein Minecraft- mit deinem Discordaccount"
